"""
Digital Marketing Content Crew
Automated content creation system for digital marketing agencies serving multiple clients

Auto-generated by CrewBuilder
"""

from crewai import Agent, Task, Crew
import os
from typing import List

# Agent Definitions
trend_researcher = Agent(
    role="Market Research Specialist",
    goal="Identify trending topics and analyze market opportunities",
    backstory="""Expert market researcher with deep knowledge of digital trends and consumer behavior patterns""",
    tools=["# web_search", "# trend_analysis", "# competitor_research"],
    max_iter=5,
    memory=True,
    verbose=True,
    allow_delegation=False
)

content_strategist = Agent(
    role="Content Strategy Expert",
    goal="Develop comprehensive content strategies aligned with business goals",
    backstory="""Senior content strategist with experience in multi-platform content planning and audience engagement""",
    tools=["# content_planning", "# seo_analysis", "# audience_research"],
    max_iter=4,
    memory=True,
    verbose=True,
    allow_delegation=True
)

content_creator = Agent(
    role="Creative Content Writer",
    goal="Create engaging, high-quality content across multiple formats",
    backstory="""Creative writer specializing in blog posts, social media, and marketing copy that converts""",
    tools=["# writing_assistant", "# image_generation", "# grammar_check"],
    max_iter=6,
    memory=True,
    verbose=True,
    allow_delegation=False
)

seo_optimizer = Agent(
    role="SEO Specialist",
    goal="Optimize all content for search engines and improve rankings",
    backstory="""Technical SEO expert with proven track record of improving organic search visibility""",
    tools=["# keyword_research", "# seo_audit", "# competitor_analysis"],
    max_iter=3,
    memory=True,
    verbose=True,
    allow_delegation=False
)

# Task Definitions  
market_research = Task(
    description="""Research trending topics in client's industry, analyze competitor content, and identify content opportunities""",
    expected_output="Comprehensive market research report with trending topics, competitor analysis, and content opportunities",
    agent=trend_researcher
)

content_strategy = Task(
    description="""Develop content strategy based on research findings, define content calendar and distribution plan""",
    expected_output="Detailed content strategy document with calendar, topics, and distribution channels",
    agent=content_strategist
)

content_creation = Task(
    description="""Create blog posts, social media content, and marketing copy based on strategy""",
    expected_output="Complete content package: blog posts, social media posts, and marketing copy",
    agent=content_creator
)

seo_optimization = Task(
    description="""Optimize all created content for SEO, add keywords, meta descriptions, and improve structure""",
    expected_output="SEO-optimized content with keywords, meta descriptions, and technical improvements",
    agent=seo_optimizer
)

# Crew Definition
crew = Crew(
    agents=[trend_researcher, content_strategist, content_creator, seo_optimizer],
    tasks=[market_research, content_strategy, content_creation, seo_optimization],
    verbose=True,
    memory=True
)

if __name__ == "__main__":
    print("🚀 Starting Digital Marketing Content Crew")
    result = crew.kickoff()
    print("✅ Crew execution completed!")
    print(f"Result: {result}")
